
## ----- Main zshrc -----



# ---------------------------------------------------------------
# -------------------------- Sources ----------------------------
# ---------------------------------------------------------------

# Source internal
if [[ -e ~/.zsh/zsh-internal ]]
then
  source ~/.zsh/zsh-internal
fi

# Source manjaro-zsh-configuration
if [[ -e ~/.zsh/manjaro-zsh-config ]]
then
  source ~/.zsh/manjaro-zsh-config
fi

# Source perso alias
if [[ -e ~/.zsh/zsh-aliases ]]
then
  source ~/.zsh/zsh-aliases
fi

# Source perso functions
if [[ -e ~/.zsh/zsh-functions ]]
then
  source ~/.zsh/zsh-functions
fi



# ---------------------------------------------------------------
# -------------------------- OhMyPosh ---------------------------
# ---------------------------------------------------------------

# OhMyPosh System
if [[ -x "$(command -v oh-my-posh)" ]]
then
  if [[ -e ~/.zsh/progs/oh-my-posh/themes/OhMyZSH.json ]]
  then
    eval "$(oh-my-posh init zsh --config ~/.zsh/progs/oh-my-posh/themes/OhMyZSH.json)"
  fi

# Portable OhMyPosh
elif [[ -e ~/.zsh/progs/oh-my-posh/oh-my-posh ]]
then
  if [[ -e ~/.zsh/progs/oh-my-posh/themes/OhMyZSH.json ]]
  then
    eval "$(~/.zsh/progs/oh-my-posh/oh-my-posh init zsh --config ~/.zsh/progs/oh-my-posh/themes/OhMyZSH.json)"
  fi
fi
