
# Source manjaro-zsh-configuration
if [[ -e ~/.zsh/manjaro-zsh-config ]]; then
  source ~/.zsh/manjaro-zsh-config
fi

# Source perso alias
if [[ -e ~/.zsh/perso-zsh-alias ]]; then
  source ~/.zsh/perso-zsh-alias
fi

# Source perso functions
if [[ -e ~/.zsh/perso-zsh-alias-functions ]]; then
  source ~/.zsh/perso-zsh-alias-functions
fi

# Portable HoMyPosh
if [[ -e ~/.zsh/oh-my-posh/oh-my-posh ]]; then
  if [[ -e ~/.zsh/oh-my-posh/themes/HoMyZSH.json ]]; then
    eval "$(~/.zsh/oh-my-posh/oh-my-posh init zsh --config ~/.zsh/oh-my-posh/themes/HoMyZSH.json)"
  fi
fi
